version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3000:3000" # 로컬 포트 3000을 컨테이너의 3000번 포트에 매핑
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run start:prod